#!/bin/bash
# GitHub Auto-Publish Script for Moltbot Skills
# Usage: ./publish-skill.sh <skill-name> [repo-name]

set -e

SKILL_NAME="${1:-beautiful-mermaid}"
REPO_NAME="${2:-moltbot-$SKILL_NAME}"
SKILL_DIR="/Users/icetomoyo/clawd/skills/$SKILL_NAME"

echo "🚀 Publishing skill: $SKILL_NAME"
echo "📦 Repository: $REPO_NAME"

# Check if skill exists
if [ ! -d "$SKILL_DIR" ]; then
    echo "❌ Skill not found: $SKILL_DIR"
    exit 1
fi

# Check GitHub CLI
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI not installed. Install with: brew install gh"
    exit 1
fi

# Check authentication
if ! gh auth status &> /dev/null; then
    echo "🔑 GitHub CLI not authenticated."
    echo "Run: gh auth login"
    exit 1
fi

# Create temporary repo directory
TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"

# Initialize git
git init
git config user.name "Moltbot Agent"
git config user.email "agent@molt.bot"

# Copy skill files
cp -r "$SKILL_DIR"/* .

# Create .gitignore if not exists
if [ ! -f ".gitignore" ]; then
    cat > .gitignore << 'EOF'
node_modules/
package-lock.json
package.json
.DS_Store
*.log
EOF
fi

# Commit
git add .
git commit -m "Initial release: $SKILL_NAME

A Moltbot skill for rendering beautiful Mermaid diagrams.
- SVG and ASCII output
- 15+ themes
- Auto-installation support

Generated by Moltbot Agent"

# Create GitHub repo and push
echo "📤 Creating GitHub repository..."
gh repo create "$REPO_NAME" \
    --public \
    --description "Moltbot skill: Render Mermaid diagrams as beautiful SVGs or ASCII art" \
    --source=. \
    --remote=origin \
    --push

# Get repo URL
REPO_URL=$(gh repo view "$REPO_NAME" --json url -q '.url')

echo ""
echo "✅ Success! Skill published to:"
echo "   $REPO_URL"
echo ""
echo "📦 Package created: /Users/icetomoyo/clawd/$SKILL_NAME.skill"

# Cleanup
cd /
rm -rf "$TEMP_DIR"

# Create .skill package for distribution
cd /Users/icetomoyo/clawd/skills
zip -r "/Users/icetomoyo/clawd/$SKILL_NAME.skill" "$SKILL_NAME/" -x "*/node_modules/*" -x "*/.git/*"

echo "🎉 Done! You can install this skill with:"
echo "   moltbot skills install $REPO_URL"
